back-og/back-log

- src/main/java/dev/auth/domain/Platform.java
- src/main/java/dev/user/domain/Email.java
- src/main/java/dev/user/domain/User.java
- src/main/java/dev/user/infrastructure/persistence/UserRepository.java
> User의 Entity, Repository 구현
> 페어 프로그래밍으로 작성
close: #11
> User의 Entity, Repository 구현

- src/main/java/dev/backlog/domain/comment/domain/Comment.java
- src/main/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepository.java
> Comment Entity, Repository 구현
> 페어 프로그래밍으로 구현
close: #15
> Comment Entity, Repository 구현

- src/main/java/dev/backlog/domain/hashtag/domain/Hashtag.java
- src/main/java/dev/backlog/domain/hashtag/infrastructure/persistence/HashtagRepository.java
- src/main/java/dev/backlog/domain/posthashtag/domain/PostHashtag.java
- src/main/java/dev/backlog/domain/posthashtag/infrastructure/persistence/PostHashtagRepository.java
📄 Summary
HashTag, PostHashTag의 Entity, Repository 구현
🍸 More
페어 프로그래밍으로 구현
close: https://github.com/back-og/back-log/issues/16
> HashTag, PostHashTag의 Entity, Repository 구현

- src/main/java/dev/backlog/common/config/JpaConfig.java
- src/main/java/dev/backlog/common/entity/BaseEntity.java
>Base entity 구현
>페어프로그래밍
close: #31
> Base entity 구현

- src/main/java/dev/backlog/domain/like/domain/Like.java
- src/main/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepository.java
> Like Entity, Repository 구현
> 페어 프로그래밍으로 구현
close: #19
> Like Entity, Repository 구현

- src/main/java/dev/backlog/domain/auth/infrastructure/JwtTokenProvider.java
- src/main/java/dev/backlog/domain/user/api/UserController.java
- src/main/java/dev/backlog/domain/user/dto/OtherUserResponse.java
- src/main/java/dev/backlog/domain/user/dto/UserDetailsResponse.java
- src/main/java/dev/backlog/domain/user/dto/UserResponse.java
- src/main/java/dev/backlog/domain/user/infrastructure/persistence/UserRepository.java
- src/main/java/dev/backlog/domain/user/service/UserService.java
> 사용자 프로필 조회 기능 구현
> 본인 프로필 조회 기능 구현
> 다른 사용자의 프로필 조회 기능 구현
> 사용자 프로필 조회 기능 구현

- build.gradle
- src/test/java/dev/backlog/common/config/ControllerTestConfig.java
> 문서화도구로 Rest DOCS + Swagger 를 적용한다.
- 의존성 추가
- 문서화를 위한 공용 코드 작성
> 문서화도구로 Rest DOCS + Swagger 를 적용한다.

- src/main/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepository.java
- src/main/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepository.java
- src/main/java/dev/backlog/domain/like/model/Like.java
- src/main/java/dev/backlog/domain/post/api/PostController.java
- src/main/java/dev/backlog/domain/post/dto/PostSliceResponse.java
- src/main/java/dev/backlog/domain/post/dto/PostSummaryResponse.java
- src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostRepository.java
- src/main/java/dev/backlog/domain/post/service/PostService.java
- src/test/java/dev/backlog/common/util/TestFixtureUtil.java
- src/test/java/dev/backlog/common/util/TestStubUtil.java
- src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepositoryTest.java
- src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepositoryTest.java
- src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
- src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostRepositoryTest.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
> 사용자별 좋아요를 누른 게시글 목록을 최신 순서로 조회 기능 구현
> `package dev.backlog.common.util` 이 경로에 TestStubUtil 클래스를 두어 테스트에 필요한 엔티티들을 생성할 수 있게끔 만들고, 이를 활용해서 테스트 코드를 작성했습니다. 이부분 피드백 부탁드립니다.
close: #5
> 사용자별 좋아요를 누른 게시글 목록을 최신 순서로 조회 기능 구현

- src/main/java/dev/backlog/domain/auth/api/AuthController.java
- src/main/java/dev/backlog/domain/auth/service/OAuthService.java
- src/main/java/dev/backlog/domain/post/api/PostController.java
- src/main/java/dev/backlog/domain/post/dto/PostSummaryResponse.java
- src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostRepository.java
- src/main/java/dev/backlog/domain/post/service/PostService.java
- src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
- src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostRepositoryTest.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
> 사용자의 시리즈 별 게시물 목록 조회 기능 구현
> 사용자의 시리즈 별 게시물 목록 조회 기능 구현
close: #25
> 사용자의 시리즈 별 게시물 목록 조회 기능 구현

- src/main/java/dev/backlog/common/config/QueryDslConfig.java
- src/main/java/dev/backlog/domain/auth/api/AuthController.java
- src/main/java/dev/backlog/domain/like/model/Like.java
- src/main/java/dev/backlog/domain/post/api/PostController.java
- src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepository.java
- src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepositoryImpl.java
- src/main/java/dev/backlog/domain/post/infrastructure/persistence/PostRepository.java
- src/main/java/dev/backlog/domain/post/model/Post.java
- src/main/java/dev/backlog/domain/post/service/PostService.java
- src/main/resources/application.yml
- src/test/java/dev/backlog/common/RepositoryTest.java
- src/test/java/dev/backlog/domain/comment/infrastructure/persistence/CommentRepositoryTest.java
- src/test/java/dev/backlog/domain/hashtag/infrastructure/persistence/HashtagRepositoryTest.java
- src/test/java/dev/backlog/domain/like/infrastructure/persistence/LikeRepositoryTest.java
- src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
- src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostHashtagRepositoryTest.java
- src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostQueryRepositoryImplTest.java
- src/test/java/dev/backlog/domain/post/infrastructure/persistence/PostRepositoryTest.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
- src/test/java/dev/backlog/domain/series/infrastructure/persistence/SeriesRepositoryTest.java
- src/test/resources/application.yml
> 좋아요 많이 받은 순서로 조회하는, 트렌딩 조회 기능 구현
> 일, 주, 월, 년 필터링 조건 추가
> 트렌딩 조회 기능 구현
> 일, 주, 월, 년 필터링 조건 추가
close: #22
> 트렌딩 조회 기능 구현

- src/main/java/dev/backlog/domain/user/api/UserController.java
- src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
> refactor: #9 사용자 프로필 수정 상태코드 변경

- src/main/java/dev/backlog/domain/user/api/UserController.java
- src/main/java/dev/backlog/domain/user/dto/UserDetailsResponse.java
- src/main/java/dev/backlog/domain/user/dto/UserResponse.java
- src/main/java/dev/backlog/domain/user/dto/UserUpdateRequest.java
- src/main/java/dev/backlog/domain/user/infrastructure/persistence/UserRepository.java
- src/main/java/dev/backlog/domain/user/model/User.java
- src/main/java/dev/backlog/domain/user/service/UserService.java
- src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
- src/test/java/dev/backlog/domain/user/service/UserServiceTest.java
> 사용자 프로필 수정
> 사용자 프로필 수정 기능 구현
> 사용자 테스트 코드 작성
close: #61
> 사용자 프로필 수정 기능 구현

- src/main/java/dev/backlog/common/UserArgumentResolver.java
- src/main/java/dev/backlog/common/config/AuthWebConfig.java
- src/main/java/dev/backlog/domain/user/api/UserController.java
- src/main/java/dev/backlog/domain/user/dto/UserPrincipal.java
- src/main/java/dev/backlog/domain/user/service/UserService.java
- src/test/java/dev/backlog/common/config/ControllerTestConfig.java
- src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
- src/test/java/dev/backlog/domain/user/service/UserServiceTest.java
> ArgumentResolver 구현 및 적용
> 
close: #65
> ArgumentResolver 적용

- src/main/java/dev/backlog/domain/post/dto/PostCreateRequest.java
- src/main/java/dev/backlog/domain/post/dto/PostUpdateRequest.java
- src/main/java/dev/backlog/domain/post/model/Post.java
- src/main/java/dev/backlog/domain/post/service/PostHashtagService.java
- src/main/java/dev/backlog/domain/post/service/PostService.java
- src/test/java/dev/backlog/common/config/ControllerTestConfig.java
- src/test/java/dev/backlog/common/fixture/DtoFixture.java
- src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
close: #80 
> 사용자의 정보를 ArgumentResolver를 통해 바인딩 받으므로 API리팩터링 및 테스트코드 변경
> 사용자의 정보를 ArgumentResolver를 통해 바인딩 받으므로 API리팩터링 및 테스트코드 변경
> 게시물 생성 API 리팩터링

- src/main/java/dev/backlog/domain/post/api/PostController.java
- src/main/java/dev/backlog/domain/post/dto/PostCreateRequest.java
- src/main/java/dev/backlog/domain/post/dto/PostUpdateRequest.java
- src/main/java/dev/backlog/domain/post/model/Post.java
- src/main/java/dev/backlog/domain/post/service/PostHashtagService.java
- src/main/java/dev/backlog/domain/post/service/PostService.java
- src/test/java/dev/backlog/common/config/ControllerTestConfig.java
- src/test/java/dev/backlog/common/fixture/DtoFixture.java
- src/test/java/dev/backlog/domain/post/api/PostControllerTest.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
- src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
close: #82 
>
API를 작성할때와 변경점이 생겨 리팩터링 진행
테스트코드 및 문서화 추가
>
토큰 ArgumentResolver 적용
테스트코드 작성
문서화
> 게시물 수정 API 리팩터링

- src/main/java/dev/backlog/common/UserArgumentResolver.java
- src/main/java/dev/backlog/domain/auth/AuthTokensGenerator.java
- src/main/java/dev/backlog/domain/auth/api/AuthController.java
- src/main/java/dev/backlog/domain/auth/dto/RefreshTokenRequest.java
- src/main/java/dev/backlog/domain/auth/model/oauth/JwtTokenProvider.java
- src/main/java/dev/backlog/domain/auth/service/OAuthService.java
- src/main/java/dev/backlog/domain/user/dto/AuthInfo.java
- src/test/java/dev/backlog/domain/auth/api/AuthControllerTest.java
- src/test/java/dev/backlog/domain/auth/service/OAuthServiceTest.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
- src/test/java/dev/backlog/domain/post/service/query/PostQueryServiceTest.java
- src/test/java/dev/backlog/domain/user/api/UserControllerTest.java
> 액세스 토큰이 만료될 경우 리프레시 토큰으로 액세스 토큰을 갱신하고,
리프레시 토큰이 만료되었을 경우 재로그인을 요청한다
>
> 토큰 갱신 기능 구현

- src/main/java/dev/backlog/common/advice/GlobalExceptionHandler.java
- src/main/java/dev/backlog/common/exception/GlobalErrorCode.java
- src/main/java/dev/backlog/domain/auth/model/oauth/JwtTokenProvider.java
- src/main/java/dev/backlog/domain/series/api/SeriesController.java
- src/main/java/dev/backlog/domain/series/dto/SeriesCreateRequest.java
- src/main/java/dev/backlog/domain/series/infra/SeriesRepositoryAdaptor.java
- src/main/java/dev/backlog/domain/series/model/repository/SeriesRepository.java
- src/main/java/dev/backlog/domain/series/service/SeriesService.java
- src/main/java/dev/backlog/domain/user/exception/UserErrorCode.java
- src/main/java/dev/backlog/domain/user/infrastructure/UserRepositoryAdapter.java
- src/test/java/dev/backlog/common/fixture/DtoFixture.java
- src/test/java/dev/backlog/domain/series/api/SeriesControllerTest.java
- src/test/java/dev/backlog/domain/series/infra/SeriesRepositoryAdaptorTest.java
- src/test/java/dev/backlog/domain/series/service/SeriesServiceTest.java
> 시리즈 생성 api 구현
- 시리즈 생성은 동적으로 진행되므로 204반환
- @Valid 발생한 예외 처리 핸들러 구현
close: #86
> 시리즈 생성 api 구현

- src/main/java/dev/backlog/domain/auth/infrastructure/kakao/client/KakaoApiClient.java
- src/main/java/dev/backlog/domain/auth/infrastructure/kakao/client/KakaoMemberClient.java
- src/main/java/dev/backlog/domain/auth/service/OAuthService.java
- src/main/java/dev/backlog/domain/user/api/UserController.java
- src/main/java/dev/backlog/domain/user/infrastructure/UserRepositoryAdapter.java
- src/main/java/dev/backlog/domain/user/model/User.java
- src/main/java/dev/backlog/domain/user/model/repository/UserRepository.java
- src/main/java/dev/backlog/domain/user/service/UserService.java
> 사용자 탈퇴 후 30일 이내 재로그인 시 탈퇴 무효하고 로그인 처리,
30일 이후 재로그인 시 예외를 던진다
>
close: #7
> 사용자 탈퇴 처리 기능 구현

- src/main/java/dev/backlog/domain/post/api/PostController.java
- src/main/java/dev/backlog/domain/post/service/PostService.java
- src/test/java/dev/backlog/domain/post/service/PostServiceTest.java
close: #92 
>
게시물 삭제 API 리팩토링
변경 사항 반영과 클린코드를 위한 리팩토링
>
게시물 삭제 API 리팩토링
변경 사항 반영과 클린코드를 위한 리팩토링
> 게시물 삭제 API 리팩토링

- src/main/java/dev/backlog/auth/service/OAuthService.java
- src/main/java/dev/backlog/user/api/UserController.java
- src/main/java/dev/backlog/user/domain/repository/UserRepository.java
- src/main/java/dev/backlog/user/dto/UserDetailsResponse.java
- src/main/java/dev/backlog/user/dto/UserUpdateRequest.java
- src/main/java/dev/backlog/user/infrastructure/UserRepositoryAdapter.java
- src/test/java/dev/backlog/user/api/UserControllerTest.java
- src/test/java/dev/backlog/user/service/UserServiceTest.java
> 회원가입 시 사용자 중복 체크
> 이미 회원가입 된 회원일 경우 예외 발생
close: #95
> 사용자 중복 체크 기능 추가

- src/main/java/dev/backlog/auth/service/OAuthService.java
- src/main/java/dev/backlog/user/domain/repository/UserRepository.java
- src/main/java/dev/backlog/user/infrastructure/UserRepositoryAdapter.java
- src/main/java/dev/backlog/user/infrastructure/jpa/UserJpaRepository.java
> 회원가입 시 사용자 중복 체크 시 발생하는 예외를 커스텀 예외로 변경
> 수정하다 보니 사용자 중복 체크 메서드가 조금 변경되었는데 새로 이슈 파기에는 작아서 한 번에 올렸습니다!
close: #89
> 사용자 커스텀 예외 적용

- src/main/java/dev/backlog/auth/service/OAuthService.java
> 소셜 회원가입 시 프로필 사진 제공을 동의하지 않았다면 기본값을 넣어준다
>
close: #114
> 프로필 사진 기본값 적용 구현

- src/main/java/dev/backlog/comment/api/CommentController.java
- src/main/java/dev/backlog/comment/domain/repository/CommentRepository.java
- src/main/java/dev/backlog/comment/dto/CreateCommentRequest.java
- src/main/java/dev/backlog/comment/infra/CommentRepositoryAdaptor.java
- src/main/java/dev/backlog/comment/service/CommentService.java
- src/test/java/dev/backlog/comment/api/CommentControllerTest.java
- src/test/java/dev/backlog/comment/service/CommentServiceTest.java
> 댓글 생성 기능 구현 및 테스트 코드 작성
> 
close: #104
> 댓글 생성 기능 구현

- src/main/java/dev/backlog/comment/api/CommentController.java
- src/test/java/dev/backlog/common/fixture/EntityFixture.java
- src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
>
테스트코드 깨지는 문제 해결
>
테스트코드 깨지는 문제 해결
> 테스트코드 깨지는 문제 해결

- src/main/java/dev/backlog/comment/api/CommentController.java
- src/main/java/dev/backlog/comment/domain/Comment.java
- src/main/java/dev/backlog/comment/dto/CommentCreateRequest.java
- src/main/java/dev/backlog/comment/dto/CommentUpdateRequest.java
- src/main/java/dev/backlog/comment/service/CommentService.java
- src/test/java/dev/backlog/comment/api/CommentControllerTest.java
- src/test/java/dev/backlog/comment/service/CommentServiceTest.java
> 댓글 수정 기능 구현 및 테스트 코드 작성
>
close: #105
> 댓글 수정 기능 구현

- src/main/java/dev/backlog/comment/api/CommentController.java
- src/main/java/dev/backlog/comment/domain/repository/CommentRepository.java
- src/main/java/dev/backlog/comment/infra/CommentRepositoryAdaptor.java
- src/main/java/dev/backlog/comment/service/CommentService.java
- src/test/java/dev/backlog/comment/api/CommentControllerTest.java
- src/test/java/dev/backlog/comment/service/CommentServiceTest.java
> 댓글 삭제 기능 구현 및 테스트 코드 작성
>
close: #121
> 댓글 삭제 기능 구현

- src/main/java/dev/backlog/auth/domain/oauth/OAuthProvider.java
- src/main/java/dev/backlog/auth/infrastructure/github/GithubTokens.java
- src/main/java/dev/backlog/auth/infrastructure/github/authCode/GithubAuthCodeRequestUrlProvider.java
- src/main/java/dev/backlog/auth/infrastructure/github/client/GithubApiClient.java
- src/main/java/dev/backlog/auth/infrastructure/github/client/GithubMemberClient.java
- src/main/java/dev/backlog/auth/infrastructure/github/config/GithubConfig.java
- src/main/java/dev/backlog/auth/infrastructure/github/config/GithubProperties.java
- src/main/java/dev/backlog/auth/infrastructure/github/dto/GithubMemberResponse.java
- src/main/resources/application.yml
> 깃허브로 소셜 로그인하는 기능 구현
>
close: #124
> 깃허브 소셜 로그인 기능 구현

- src/main/java/dev/backlog/common/config/PostAccessStrategyMapConfig.java
- src/main/java/dev/backlog/post/domain/repository/PostCacheRepository.java
- src/main/java/dev/backlog/post/infra/PostCacheRepositoryAdaptor.java
- src/main/java/dev/backlog/post/service/query/PostAccessStrategy.java
- src/main/java/dev/backlog/post/service/query/PostQueryService.java
- src/main/java/dev/backlog/post/service/query/PrivatePostAccessStrategy.java
- src/main/java/dev/backlog/post/service/query/PublicPostAccessStrategy.java
- src/test/java/dev/backlog/comment/infra/CommentRepositoryAdaptorTest.java
- src/test/java/dev/backlog/comment/service/CommentServiceTest.java
- src/test/java/dev/backlog/common/fixture/EntityFixture.java
- src/test/java/dev/backlog/like/infra/PostLikeRepositoryAdaptorTest.java
- src/test/java/dev/backlog/like/service/PostLikeServiceTest.java
- src/test/java/dev/backlog/post/domain/repository/PostQueryRepositoryTest.java
- src/test/java/dev/backlog/post/infra/jpa/PostHashtagJpaRepositoryTest.java
- src/test/java/dev/backlog/post/service/PostServiceTest.java
- src/test/java/dev/backlog/post/service/query/PostQueryServiceTest.java
- src/test/java/dev/backlog/post/service/query/PrivatePostAccessStrategyTest.java
- src/test/java/dev/backlog/post/service/query/PublicPostAccessStrategyTest.java
> 비공개 게시물 조회 시, 사용자 검증 로직 추가
> 비공개 게시물 조회 시, 사용자 검증 로직 추가
close: #101
> 비공개 게시물 조회 시, 사용자 검증 로직 추가

- build.gradle
- lombok.config
>Jacoco 라이브러리 적용
>Jacoco 라이브러리 적용
> Jacoco 라이브러리 적용

- build.gradle
- src/main/java/dev/backlog/common/config/HTMLCharacterEscapes.java
- src/main/java/dev/backlog/common/config/HttpMessageConverterConfig.java
- src/main/java/dev/backlog/reply/domain/Reply.java
- src/test/java/dev/backlog/comment/service/CommentServiceTest.java
- src/test/java/dev/backlog/common/HTMLCharacterEscapesTest.java
>게시물 저장 시 검증 추가
- XSS 방지
- html escape
>게시물 저장 시 검증 추가
- XSS 방지
- html escape
close: #133
> 게시물 저장 시 검증 추가
